log_user/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from log_user import views


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^login/$', views.login1,name='login' ),
    url(r'^register/$', views.register1, name='register'),
    url(r'^regsuccess/$', views.register_sussess, name = 'success'),
    url(r'^logout/$', views.logout1, name='logout'),

    
    
    ]

mlshopping/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from receipt import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.start_page, name='home'),
    
    url(r'^paragony/', include('receipt.urls',namespace='paragony')),
    url(r'^', include('log_user.urls',namespace='loginapp')),
    
    
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receipt/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from receipt import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^receipt-list/$', views.lista_paragonow, name='lista_paragonow'),
    url(r'^receipt-form/$', views.add_receipt, name='add_receipt'),
    ]

log_user/models.py
from django.db import models

# Create your models here.

receipt/models.py
from django.db import models
from django.contrib.auth.models import User


class Paragon(models.Model):
    image = models.FileField()
    image_data = models.TextField(null=True, blank=True, default='Processing image... Refresh to check for results. If that doesnt help please wait or do something else one the website')
    user1 = models.ForeignKey(User, blank=True, null=True)

def __str__(self):
        return str(self.image)


class ParagonItems(models.Model):
    id_paragonu =models.ForeignKey(Paragon, blank=True, null=True)  
    cena = models.CharField(max_length=120, null=True, blank=True)
    produkt = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return (self.produkt)

log_user/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':"User name"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))
    class Meta:
        model = User
        fields = ['username', 'password']

receipt/forms.py
from django import forms
from .models import Paragon


class ParagonForm(forms.ModelForm):
    class Meta:
        model = Paragon
        fields =('image',)

log_user/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login,logout
from django.views.generic import View
from .forms import UserForm
from django.core.urlresolvers import reverse



def logout1(request):
    user = request.user.username
    logout(request)
    context = {'user':user}
    return render (request, 'log_user/logout.html', context)

def register_sussess(request):
    return render (request, 'log_user/successful_registration.html')

def login1(request):
    form = UserForm ()
    context = {'form':form}
    
    if request.method == 'POST':
        form = UserForm(request.POST)

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate (username=username, password=password)
        if user is not None:
            login(request, user)
           # return redirect('paragony:lista_paragonow')
            return redirect('home')
        else:
            context['flag'] = True
    
    return render(request, 'log_user/login.html', context)


def register1(request):
    form = UserForm ()
    context =  {'form': form}
    
    if request.method == 'POST':
        form = UserForm (request.POST)

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate (username=username, password=password)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(password)
            user.save()
            return HttpResponseRedirect('/regsuccess/')
        else:
            context['flag'] = True
    return render(request, 'log_user/register.html', context)

@login_required
def user_loged(request):
    user=request.user.username
    quaryset = Pytania.objects.filter(user=user).values('carddeck').distinct()
    context = {'pytania':quaryset,}
    return render (request, 'user_loged.html', context)

receipt/views.py
from django.shortcuts import render, redirect
from .forms import  ParagonForm
from .models import Paragon
import pytesseract

from .tasks import items_from_image

from PIL import Image, ImageFilter

def start_page(request):
    return render(request,'base.html')


def lista_paragonow(request):
    qs = Paragon.objects.filter(user1=request.user)[::-1]  
    context={'qs':qs}
    return render(request, 'receipt/paragon_list2.html', context)


def add_receipt(request):
    if request.method == 'POST':
        form =ParagonForm(request.POST, request.FILES)
        print(request.FILES['image'])
        if form.is_valid():
            new_rec =form.save(commit=False)
            new_rec.user1=request.user            
            new_rec.save()
            items_from_image.delay(new_rec.image.name)
            return redirect('paragony:lista_paragonow')
    else:
        form =ParagonForm()
    
    context = {'form':form}
    return render (request, 'receipt/paragon_form.html', context)

log_user/templates/log_user/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
	    <div class="row">
		      <div class="col-md-4"></div>
		        <div class="col-md-4">


<h2 class="form-signin-heading">Please sign in</h2>
	<form method="POST" >{% csrf_token %}
        {{ form }}
	<br>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
	<br>
	{% if flag %}
	<p class="text-center text-danger"> Something went wrong. Try again. </p>
	{% endif %}

</div>
			  <div class="col-md-4"></div>
	    </div>




    </div> <!-- /container -->
    {% endblock %}

log_user/templates/log_user/logout.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	  <div class="col-md-4"></div>
	    <div class="col-md-4">
		    <h4>You are now succesfully loged out. <br>
	    
	    </div>
	      <div class="col-md-4"></div>
</div>


{% endblock %}

log_user/templates/log_user/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
	    <div class="row">
		      <div class="col-md-4"></div>
		        <div class="col-md-4">


<h2 class="form-signin-heading">Please register</h2>
	<form method="POST" >{% csrf_token %}
        {{ form }}
	<br>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
	</form>
	<br>	
       	{% if flag %}
        <p class="text-center text-danger"> User already exists. </p>
        {% endif %}



</div>
			  <div class="col-md-4"></div>
	    </div>




    </div> <!-- /container -->
    {% endblock %}

log_user/templates/log_user/successful_registration.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	  <div class="col-md-4"></div>
	    <div class="col-md-4">
		    <h4>You are now succesfully registered. <br>
			    Clik here to <a href = '/login/'>log in </a></h4>
	    
	    </div>
	      <div class="col-md-4"></div>
</div>


{% endblock %}

log_user/templates/log_user/user_loged.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	  <div class="col-md-2"></div>
	    <div class="col-md-8">
	   
		    <p>  Hello, {{ user }} bellow are your cards:</p></br>
		

		
		   <table class='table table-bordered table-striped table-hover'>
		      <thead>
		      <tr>
		      	<th class ='text-center'> Name </th>
			<th class ='text-center'> Start </th>
			<th class ='text-center'> Edit </th>
			<th class ='text-center'> Delete </th>
		      </tr>
		      </thead>
			
		      <tbody>
		   	 {% for obj in pytania %}
		   		<tr>
				<td class="text-center"> {{ obj.carddeck }}</td>
				<td class="text-center" ><a href = '/cards/{{ user }}/{{ obj.carddeck }}/0/qq'> start learning </a></td>
				<td class="text-center"><a href = '/cards/edit/{{ user }}/{{ obj.carddeck }}'>edit</a></td>
				<td class="text-center"><a href = '/cards/delete/{{ user }}/{{ obj.carddeck }}'>delete</a> </td>
				</tr>
<!--	 <h4><a href = '/{{ obj.carddeck }}'> {{ obj.carddeck }}</a></h4>  -->
			 {% endfor %}
		      </tbody>
		   </table>
	<a href="/addquestion" class="btn btn-info" role="button">Add Card</a>		  



	    </div>
	      <div class="col-md-2"></div>
</div>


{% endblock %}

receipt/templates/receipt/base_paragon.html
{% extends 'base.html' %}

{% block content %}
<!--    <div class="container"> -->


      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Paragony</h1>
        <p>Here you can add your receipts and analyse your past expenses. </p>

        <p>
        <a class="btn btn-lg btn-primary" href="{% url 'paragony:lista_paragonow' %}" role="button">lista paragonow</a>
         <a class="btn btn-lg btn-primary" href="{% url 'paragony:add_receipt' %}" role="button">wprowadz paragon</a>


        </p>

       



      </div>








      <!--    </div>   -->  <!-- /container --> 
    {% endblock %}


	    {% block jquery %}
			  
			   {% endblock %}

			   {% block dupa %} {% endblock %}

receipt/templates/receipt/paragon_form.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
	    <div class="row">
		      <div class="col-md-4"></div>
		        <div class="col-md-4">


<h2 class="form-signin-heading">Upload your receipt</h2>
	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
	<br>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Upload</button>
	</form>
	<br>
	{% if flag %}
	<p class="text-center text-danger"> Something went wrong. Try again. </p>
	{% endif %}

</div>
			  <div class="col-md-4"></div>
	    </div>

    </div> <!-- /container -->





    {% endblock %}


	    {% block jquery %}
			  
			   {% endblock %}

			   {% block dupa %} {% endblock %}

receipt/templates/receipt/paragon_list2.html
{% extends 'base.html' %}

{% block content %}
<!--    <div class="container"> -->



	{% for i in qs %}
	    <div class="row">
		      <div class="col-md-4">

	<a href={{ i.image.url }} >
	      	<img src={{ i.image.url }} alt="Mountain View" style="width:304px;height:228px;">
		</a>
	<br>

	<br>






			</div>
		        <div class="col-md-4">
			
			{% if i.paragonitems_set.all %}

 {#			{% for itemka in i.paragonitems_set.all %}  #}
		


<table class='table table-bordered table-striped table-hover'>
                      <thead>
                      <tr>
                        <th class ='text-center'> Produkt </th>
                        <th class ='text-center'> Cena </th>
                      </tr>
                      </thead>

                      <tbody>
                         {% for itemka in i.paragonitems_set.all %}
                                <tr>
                                <td class="text-left"> {{ itemka.produkt }}</td>
                                <td class="text-center" >{{ itemka.cena }}</td>
                                </tr>
                         {% endfor %}
                      </tbody>
                   </table>

















{#			{{ itemka.produkt }} #} 
{#			{{ itemka.cena }}  #}
{#			{% endfor %}  #}


			{% else %}
			{{ i.image_data }}

			{% endif %}

			</div>
			  <div class="col-md-4">  
				
			  </div>
	    </div>
	    <hr>
	{% endfor %}

	<!--    </div>  --> <!-- /container --> 













    {% endblock %}


	    {% block jquery %}
			  
			   {% endblock %}

			   {% block dupa %} {% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html>

	<head>

		<title>MlShopping</title>


	</head>	
	
	
<body>


<div class="container" style = 'text-align:center;'>

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
	    <a class="navbar-brand" href="{% url 'home' %}">MlShopping</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
	      {% if user.is_authenticated %}
	      <li><a href="{% url 'paragony:lista_paragonow' %}">Receipt List</a></li>
	      <!--      <li><a href="/about/">About</a></li> -->
	      <!--          <li><a href="#">Contact</a></li> -->
	      {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
	{% if user.is_authenticated %}
	    	    <li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/logout/">Log out</a></li>
		  <li><a href="{% url 'paragony:lista_paragonow' %}">Receipts</a></li>

                </ul>
              </li>
	{% else %}
              <li class="active"><a href="/login/">Log in <span class="sr-only">(current)</span></a></li>
              <li><a href="/register/">Register</a></li>
	{% endif %}
	    </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
</nav>

      {% block content %}

<div class="jumbotron">
        <h1>Paragony</h1>
        <p>Here you can add your receipts and analyse your past expenses. </p>

	{% if user.is_authenticated %}

        <p>
        <a class="btn btn-lg btn-primary" href="{% url 'paragony:lista_paragonow' %}" role="button">lista paragonow</a>
         <a class="btn btn-lg btn-primary" href="{% url 'paragony:add_receipt' %}" role="button">wprowadz paragon</a>
        </p>
	
	{% else %}
	<p>
	<a class="btn btn-lg btn-primary" href="{% url 'loginapp:register' %}" role="button">Sign up</a>
	</p>
{% endif %}
	
      </div> <!-- jumbo -->


	{% endblock %}
</div> <!-- /container -->





<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

 <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!--    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <script>
	

	$(document).ready(function(){
	{% block jquery %}
		
		<!--		alert('hello world'); -->



		{% endblock %}	
	
   
	});



    </script> 
   
   
   
   
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>